name: Update Docker Hub Pull Counts

on:
  schedule:
    # Run at 0:00 UTC every day
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-pull-counts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Update pull counts
        run: python update_pull_counts.py
      
      - name: Check for changes
        id: git-check
        run: |
          git status --porcelain
          echo "::set-output name=modified::$(if git status --porcelain | grep -q 'README.md'; then echo 'true'; else echo 'false'; fi)"
      
      - name: Commit and push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update Docker Hub pull counts - $(date +'%Y-%m-%d')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}